// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxbxfdbscqlruzxaorah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YnhmZGJzY3FscnV6eGFvcmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODA1NDIsImV4cCI6MjA3MTg1NjU0Mn0.O9wiDs0-ihf9RUGMwbMagL8_28L9R3-QlF249dLqLXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});